parameters:
- name: orgId
  displayName: Organization Id
  type: string
- name: location
  displayName: Location
  type: string
- name: keyVaultName
  displayName: Key Vault
  type: string

trigger: none

name: CreateRPortVM

variables:
  deploymentName: 'CreateRPortSvr'
  vmImageName: 'ubuntu-latest'
  azureServiceConnection: 'github.com_dalapagos'
  admin-vm-password: '${{ parameters.orgId }}-Tnls-VmPass'
  resourceGroupName: 'Dalapagos-${{ parameters.orgId }}'
  keyVault: ${{ parameters.keyVaultName }}
  vmName: 'dlpg-tnls-vm-${{ lower(parameters.orgId) }}'
  fqdn: 'dlpg-tnls-${{ lower(parameters.orgId) }}.${{ lower(parameters.location) }}.cloudapp.azure.com'
  templateFile: 'src/Dalapagos.Tunnels.Core/Scripts/create-rportsvr.bicep'

pool:
  vmImage: $(vmImageName)

steps:
- task: AzureKeyVault@2
  displayName: Get VM pwd from Key Vault
  inputs:
    azureSubscription: $(azureServiceConnection)
    KeyVaultName: $(keyVault)
    SecretsFilter: $(admin-vm-password)

- task: AzureCLI@2
  name: DeployBicep
  displayName: Create VM
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    useGlobalConfig: false
    inlineScript: |
      az --version
      if [ "true" == $(az group exists --name $(resourceGroupName)) ]; then :; else az group create --name $(resourceGroupName) --location ${{ parameters.location }}; fi;
      az deployment group create --name $(deploymentName) --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters 'vmName=$(vmName)' 'vmSize=Standard_B1s' 'adminPassword=$(admin-vm-password)'

- task: AzureCLI@2
  name: BicepOutput
  displayName: Get Outputs from VM
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
      $out = az deployment group show -g $(resourceGroupName) -n $(deploymentName) | convertfrom-json | foreach properties | foreach outputs

      $provisionOutputs = [PSCustomObject]@{}
      $out | Get-Member -MemberType NoteProperty | ForEach-Object {

          $name = $_.name
          $provisionOutputs | Add-Member -MemberType NoteProperty -Name $name -value $out.$name.value
          Write-Host "##vso[task.setvariable variable=$($name);isOutput=true]$($out.$name.value)"
      }

      $provisionOutputs

- task: AzureCLI@2
  name: InstallRport
  displayName: Install RPort on VM
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Installing sshpass."
      sudo apt-get install sshpass
      sh src/Dalapagos.Tunneling.Core/Scripts/install-rport.sh $(admin-vm-password) $(BicepOutput.sshUserIp) $(fqdn)
      sshpass -p $(admin-vm-password) scp "$(BicepOutput.sshUserIp)":./rportd-installation.txt ./
      RPORTPWD="$(echo $(grep Password rportd-installation.txt) | cut -d':' -f2 | sed -e 's/^[[:space:]]*//')"
      echo "##vso[task.setvariable variable=ARPortPwd;isOutput=true]$RPORTPWD"
      sshpass -p $(admin-vm-password) scp "$(BicepOutput.sshUserIp)":./fingerprints.txt ./
      FINGRPRNT="$(echo $(grep ED25519 fingerprints.txt) | cut -d':' -f2 | cut -d' ' -f1)"
      echo "##vso[task.setvariable variable=ARPortFp;isOutput=true]$FINGRPRNT"

- task: AzureCLI@2
  displayName: Save RPort Password
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Saving RPort password to Key Vault."
      az keyvault secret set --name '${{ parameters.orgId }}-Tnls-Pass' --vault-name $(keyVault) --value $(InstallRport.ARPortPwd)

- task: AzureCLI@2
  displayName: Save RPort Fingerprint
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Saving RPort vm fingerprint to Key Vault."
      az keyvault secret set --name '${{ parameters.orgId }}-Tnls-Finger' --vault-name $(keyVault) --value $(InstallRport.ARPortFp)
