parameters:
- name: location
  displayName: Location
  type: string
- name: resourceGroupName
  displayName: Resource Group
  type: string

trigger: none

name: DeployTunnelingInfra

variables:
  prefix: 'dlpg-tnls'
  deploymentName: 'DeployTunnelingInfra'
  keyVaultName: $(prefix)-key-vault
  logAnalyticsWorkspaceName: $(prefix)-log-analytics
  appInsightsName: $(prefix)-app-insights
  containerRegistryName: $(prefix)-container-registry
  containerAppEnvName: $(prefix)-container-app-env
  azureServiceConnection: 'DalapagosServiceP'
  templateFile: 'iac/core/main.bicep'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  name: DeployBicep
  displayName: Create Infrastructure
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    useGlobalConfig: false
    inlineScript: |
      az --version
      if [ "true" == $(az group exists --name ${{ parameters.resourceGroupName }}) ]; then :; else az group create --name ${{ parameters.resourceGroupName }} --location ${{ parameters.location }}; fi;
      az deployment group create --name $(deploymentName) --resource-group ${{ parameters.resourceGroupName }} --template-file $(templateFile) --parameters 'location=${{ lower(parameters.location) }}' 'logAnalyticsWorkspaceName=$(logAnalyticsWorkspaceName)' 'appInsightsName=$(appInsightsName)' 'containerRegistryName=$(containerRegistryName)' 'containerAppEnvName=$(containerAppEnvName)' 'keyVaultName=$(keyVaultName)'
